### ISSUE TITLE
some comments

### ISSUE THREAD

**Issue by lhecht** [thatlittleboy/TeXstudio-Qt-Stylesheet#1]
Hey thank you for ordering the whole stylesheet thing into one easy accesible topic.

Nevertheless I have some small comments:
- Maybe you should mention in the readme, that one has to replace the "user" in the stylesheet. 
- Your pictures are not up to date anymore, because some buttons changed, at least, when i use the stylesheet.
- For my taste the scroll bars are way too large, so I replaced them with the stylesheet provided in the old topic. Maybe you could add them as an option somewhere? I dont know what the best way to do it would be, because I have totally no idea of Qt.

![screenshottexstudio](https://user-images.githubusercontent.com/42421148/44781162-ee302c00-ab83-11e8-8c10-1cc803fc5d95.png)

**Comment by thatlittleboy** [comment]
1. PR merged.
2. Yeah, I've been meaning to redo the images.. I'll get around to doing it soon. (I didn't think this repo would be seen by many people, so I was procrastinating a bit. :p)
3. I'm not quite sure what you mean by "add as an option". (where?) All the relevant settings are under `QScrollBar`, esp the `width`/`height` properties.

**Comment by thatlittleboy** [comment]
2. I've updated the README with up to date pictures. Any other images you think would be representative?

3. I reduced the width of the scrollbars -- I agree they were a tad too "thick". (see the new sample imgs)

**Comment by lhecht** [comment]
Yes that looks much better.  Thank you.

to 3.: Totally agreed that one can do that oneself. Just because I felt not able to do it myself I copied from an older version of a stylesheet which was uploaded in the discussion on the texstudio repository. I think now that it is changed, that is fine. (You must know, that I never used QS or anything similar myself.)

Maybe there is a possibility to let more people know about this gem? I mean the developers said, that this has no priority to them, so it won't be a normal feature of texstudio but I really enjoy it like that. I got asked from other people in the library, where I got this from :). So maybe they could add this as a betafeature in their build?

to 2.: Maybe you could show the settings or upload a file with the syntaxhighlighting for the editor. Or if you want, I can give you mine. So that one could get that as well. I mean, if a landed here I want the full package, right?

**Comment by thatlittleboy** [comment]
I'm glad you like it :). 

> I got asked from other people in the library, where I got this from :). So maybe they could add this as a betafeature in their build?

If they do include my dark QSS in as a beta feature, it would become something that they would need to maintain. So I would be inclined to think that the devs would prefer to maintain status quo until the various UI clashes and inconsistencies are sorted out (I mention some in my README, and also raised to Tim et al. in the main thread).

On my end, I'm also not comfortable promoting this repo until the issues are all fixed. The reason for me putting this up on my repo is 

(i) to give others some ideas on what the qss is capable of changing and 

(ii) guide them along which part of the UI is affected by which properties in the qss file via my comments within (so they don't have to trial and error as I did, looking for the property that changes the toolbar colour, for example).


---------------------

Ok, good point. I'll do some cleaning up of my options file and upload it over the weekend.

**Comment by lhecht** [comment]
ok. hopefully people find it :)
